### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by SolivagantAI** [cLineman/CapStoneProject#7]
**Presentation**
- [ ] Practice presentation
- [ ] Deliver the goods
- [ ] Celebrate

**Production**
- [ ] Consolidate areas into separate notebooks
    * [ ] Cleaning
    * [ ] Exploration
    * [ ] Features
    * [ ] Analysis
    * [ ] Presentation
- [ ] Build non-technical presentation
- [ ] Outline presentation roles and responsibilities
- [ ] Build readme

**Analysis**
- [ ] Create final analyses
- [x] Develop business recommendations
- [ ] Create visualizations

**Build Business Case**
- [x] Select top avenues for presentation
- [x] Decide characteristics needed in final presentation
- [x] Distribute tasks to team

**Exploration**
- [x] Map each data set
- [x] Identify at least 3 potential links in the data
- [x] Examine trends
- [x] Deep dive into most promising leads

**Cleaning**
- [x] Import all files
- [x] Clean...  (check for duplicates, formatting, nulls)
    * [x] movie_gross
    * [x] movie_info
    * [x] reviews
    * [x] movies
    * [x] movie_budgets
    * [x] im.db

**Comment by SolivagantAI** [comment]
Areas of Focus
1. Directors
2. Season
3. Genre
4. Profit Ratios
